#!/usr/bin/python
import csv

csvfile = open('<path_to_csv_file>', 'r').readlines() #Open CSV file
filename = 1 #Initialize filename for the first csv file
for i in range (len(csvfile)):
	if i % 40000 == 0:
		open(str(filename) + '.csv', 'w+').writelines(csvfile[i:i+40000]) #write up to 40k lines to the csv file
		filename += 1
